### ISSUE TITLE
UE 5.1

### ISSUE THREAD

**Issue by iamsince1998** [xsolla/store-ue4-sdk#145]
hi , please tell me to use it in ue 5.1

**Comment by LeonidRatanov** [comment]
Hello, @iamsince1998 
We will release version with 5.1 support in January after New Year holidays

**Comment by iamsince1998** [comment]
> Hello, @iamsince1998 We will release version with 5.1 support in January after New Year holidays

Thanks ❤️

**Comment by kseniashabalina** [comment]
Hi, the plugin for ue5.1 is already available on github. We need a little more time to publish it on the marketplace
