### ISSUE TITLE
Unreal Editor crashes when attempting to authorize with "Encrypt Cached Credentials" enabled

### ISSUE THREAD

**Issue by kalkulator777** [xsolla/store-ue4-sdk#153]
Steps to reproduce:
1. Create project
2. Go to Xsolla Settings and enable "Encrypt Cached Credentials" and set key
3. Create simple widget for authorize
4. Try to authorize
5. Get crash with 
`Assertion failed: Key.Num() == sizeof(FAES::FAESKey::Key) [File:D:\Projects\ProjectName\Plugins\XsollaSDK\Source\XsollaLogin\Private\XsollaLoginSave.cpp] [Line: 108]`

**Comment by olga-salina** [comment]
Hi @kalkulator777 !
The Encrypt Cached Credentials key must be a base64 string that will decode into a 32 character string.
